### ISSUE TITLE
can't start repl via lein repl

### ISSUE THREAD

**Issue by Velrok** [jolby/rincanter#5]
I followed your example but I can't get a repl running:

``` bash
$ lein version
Leiningen 2.0.0 on Java 1.7.0_21 Java HotSpot(TM) 64-Bit Server VM

$ lein repl
Exception in thread "main" java.net.SocketException: Malformed reply from SOCKS server
    at java.net.SocksSocketImpl.readSocksReply(SocksSocketImpl.java:128)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:502)
    at java.net.Socket.connect(Socket.java:579)
    at java.net.Socket.connect(Socket.java:528)
    at java.net.Socket.<init>(Socket.java:425)
    at java.net.Socket.<init>(Socket.java:208)
    at clojure.tools.nrepl$connect.doInvoke(nrepl.clj:177)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.tools.nrepl.ack$send_ack.invoke(ack.clj:47)
    at clojure.tools.nrepl.server$start_server.doInvoke(server.clj:139)
    at clojure.lang.RestFn.invoke(RestFn.java:619)
    at user$eval1237.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:6511)
    at clojure.lang.Compiler.eval(Compiler.java:6501)
    at clojure.lang.Compiler.eval(Compiler.java:6477)
    at clojure.core$eval.invoke(core.clj:2797)
    at clojure.main$eval_opt.invoke(main.clj:297)
    at clojure.main$initialize.invoke(main.clj:316)
    at clojure.main$null_opt.invoke(main.clj:349)
    at clojure.main$main.doInvoke(main.clj:427)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)
REPL server launch timed out.
```

**Comment by Velrok** [comment]
Other projects are failing too. So this is not related to the project but my update to java 1.7
